module.exports = {
  boarding: {
    dog: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    cat: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    reptile: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    bird: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    small_pets: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
  },
  daycare: {
    dog: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    cat: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    reptile: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    bird: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    small_pets: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
  },
  drop_in: {
    dog: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    cat: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    reptile: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    bird: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    small_pets: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
  },
  walking: {
    dog: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    cat: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    reptile: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
  },
  grooming: {
    dog: {
      extra_charge_breed: false,
      teeth_and_breath: false,
      coat_conditioner: false,
      shampoo: false,
      drop_off: false,
    },
    cat: {
      extra_charge_breed: false,
      teeth_and_breath: false,
      coat_conditioner: false,
      shampoo: false,
      drop_off: false,
    },
    puppy: {
      extra_charge_breed: false,
      teeth_and_breath: false,
      coat_conditioner: false,
      shampoo: false,
      drop_off: false,
    },
    kitten: {
      extra_charge_breed: false,
      teeth_and_breath: false,
      coat_conditioner: false,
      shampoo: false,
      drop_off: false,
    },
  },
  training: {
    dog: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    cat: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
    bird: {
      pick_up: false,
      trim_brush: false,
      drop_off: false,
      bathing: false,
      walking: false,
    },
  },
  aquarist: {
    saltwater: {
      service1: false,
      service2: false,
      service3: false,
      service4: false,
      service5: false,
      service6: false,
    },
    freshwater: {
      service1: false,
      service2: false,
      service3: false,
      service4: false,
      service5: false,
      service6: false,
    },
    planted_tank: {
      service1: false,
      service2: false,
      service3: false,
      service4: false,
      service5: false,
      service6: false,
    },
  },
};
