module.exports = {
  boarding: {
    dog: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    cat: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    reptile: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    bird: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    small_pets: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
  },
  daycare: {
    dog: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    cat: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    reptile: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    bird: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
    small_pets: {
      spacesAvailable: 0,
      pottyBreak: null,
      isFlexible: false,
      cancellation: null,
      petSize: null,
      petPair: null,
      isSharingSpace: false,
    },
  },
  walking: {
    dog: {
      isFlexible: false,
      cancellation: null,
    },
    cat: {
      isFlexible: false,
      cancellation: null,
    },
    reptile: {
      isFlexible: false,
      cancellation: null,
    },
  },
  drop_in: {
    dog: {
      spacesAvailable: 0,
      isFlexible: false,
      cancellation: null,
    },
    cat: {
      spacesAvailable: 0,
      isFlexible: false,
      cancellation: null,
    },
    reptile: {
      spacesAvailable: 0,
      isFlexible: false,
      cancellation: null,
    },
    bird: {
      spacesAvailable: 0,
      isFlexible: false,
      cancellation: null,
    },
    small_pets: {
      spacesAvailable: 0,
      isFlexible: false,
      cancellation: null,
    },
  },
  grooming: {
    dog: {
      excludeBreed: [],
      isFlexible: false,
      cancellation: null,
    },
    puppy: {
      excludeBreed: [],
      isFlexible: false,
      cancellation: null,
    },
    cat: {
      excludeBreed: [],
      isFlexible: false,
      cancellation: null,
    },
    kitten: {
      excludeBreed: [],
      isFlexible: false,
      cancellation: null,
    },
  },
  aquarist: {
    freshwater: {},
    planted_tank: {},
    saltwater: {},
  },
};
